#!/usr/bin/env python
# -*- coding: utf8 -*-
import socket

ClientMultiSocket = socket.socket()
host = '127.0.0.1'
port = 1234


print('Waiting for server response...')
try:
	ClientMultiSocket.connect((host, port))
except socket.error as e:
	print(str(e))

res = ClientMultiSocket.recv(1024)
#i = 0

# This loop keeps checking for chips. If one is near it will get the UID and au>

str =  "136,4,11,52"

ClientMultiSocket.send(str.encode('utf-8'))
data = ClientMultiSocket.recv(1024)
print (data)

ClientMultiSocket.close()

